# .goreleaser.yml 配置文件
# 详细文档: https://goreleaser.com/

version: 2

before:
  hooks:
    # 在构建前运行测试，设置环境变量SKIP_GIT_TESTS=true跳过依赖git命令的测试
    - env SKIP_GIT_TESTS=true go test -v ./... || { echo "测试失败"; exit 1; }
    # 确保依赖是最新的
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # 主要命令
    main: ./cmd/git-work-log/main.go
    # 二进制文件名模板
    binary: git-work-log
    # 构建标记
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE
      - prompts/*
  - id: zip-archives
    formats:
      - zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE
      - prompts/*

checksum:
  name_template: 'checksums.txt'

snapshot: {}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: git-work-log
    ids: [default]
    repository:
      owner: kway-teow
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: https://github.com/kway-teow/git-work-log
    description: 一个基于Git提交记录自动生成报告的工具，使用Google Gemini AI进行智能总结
    license: MIT
    test: |
      system "#{bin}/git-work-log --help"
    install: |
      bin.install "git-work-log"
      prefix.install "prompts"
