name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
        env:
          SKIP_GIT_TESTS: "false"  # 设置为 true 可以跳过依赖 git 命令的测试

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Check if prompts directory exists
        run: |
          if [ ! -d "prompts" ]; then
            echo "Error: prompts directory is missing"
            exit 1
          fi
          if [ ! -f "prompts/basic.txt" ] || [ ! -f "prompts/detailed.txt" ] || [ ! -f "prompts/targeted.txt" ]; then
            echo "Error: one or more prompt template files are missing"
            exit 1
          fi
